name: Publish packages on NPM
on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
    steps:
      - name: install-build-tools
        uses: jdx/mise-action@d20b46e041ee9e28e7b67d713f4df93a72358b54
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'
      - run: corepack enable
      - run: yarn
      - name: Run tsc
        run: yarn tsc
      - name: Build all packages
        run: yarn build:all
      - name: Generate Backstage package metadata
        run: yarn backstage-cli repo fix --check --publish
      - name: Publish datadog-entity-sync-node
        run: yarn workspace @datadog/backstage-plugin-datadog-entity-sync-node npm publish --access public
        env:
          COREPACK_ENABLE_DOWNLOAD_PROMPT: 0
      - name: Publish datadog-entity-sync-backend
        run: yarn workspace @datadog/backstage-plugin-datadog-entity-sync-backend npm publish --access public
        env:
          COREPACK_ENABLE_DOWNLOAD_PROMPT: 0
